---
title: "run JAGS"
author: "Daniel Hocking"
date: "October 3, 2014"
output: html_document
---


NO, ar(2)? doesn't seem worth it
YES, keep cubic? if not, add q?

structure on ar(), try RE by dOY

correlation of ar with other variables, airTemplagged1 correlated?

```{r results = 'hide', warning=FALSE, message=FALSE}
library(knitr)
library(ggplot2)
library(ggmcmc) # this uses plyr which conflicts with dplyr and makes group_by not work. make sure to load dplyr after this
#detach(package:plyr)
library(nlme)
library(devtools)
install_github("Conte-Ecology/conteStreamTemperature")
library(conteStreamTemperature)
library(beepr)
library(dplyr)

baseDir <- getwd() # works as long as you have the project loaded in RStudio - does not work for kniting

dataInDir <- paste0(baseDir, '/dataIn/')
dataOutDir <- paste0(baseDir, '/dataOut/')
dataLocalDir <- paste0(baseDir, '/localData/')
graphsDir <- paste0(baseDir, '/graphs/')

# load standardized and formatted data created with the 3-statModelPrep.Rmd script
load(paste0(dataOutDir, 'tempDataSync.RData'))
tempDataSyncS$river <- 'WEST BROOK'
tempDataSyncS$river[ tempDataSyncS$site == 'MAUSGS_WB_MITCHELL' ] <- 'WB MITCHELL' 
tempDataSyncS$river[ tempDataSyncS$site == 'MAUSGS_WB_OBEAR' ] <- 'WB OBEAR' 
tempDataSyncS$river[ tempDataSyncS$site == 'MAUSGS_WB_JIMMY' ] <- 'WB JIMMY' 
tempDataSyncS$riverOrdered <- factor(tempDataSyncS$river,levels=c('WEST BROOK','WB JIMMY','WB MITCHELL','WB OBEAR'), ordered=T)


# merge in env data to get flow
load(paste0(dataOutDir, 'etWB.RData'))
et$dateDate <- as.Date(et$date) # to match tempDataSyncS
et$riverOrdered <- factor(et$site,levels=c('WEST BROOK','WB JIMMY','WB MITCHELL','WB OBEAR'), ordered=T)

tempDataSyncS <- merge(x=tempDataSyncS, y=et[,c('riverOrdered','flow','dateDate')], 
                       by.x=c('riverOrdered','date'),
                       by.y=c('riverOrdered','dateDate'),
                       all.x=T)

# standardize flow by site
tempDataSyncS <- 
tempDataSyncS %>%
group_by(site) %>%
  mutate( flowS = ( flow - mean(flow,na.rm = TRUE) ) / sd(flow,na.rm = TRUE) )

# there are 10 flows with NA., set to 0
#tempDataSyncS$flowS[is.na(tempDataSyncS$flowS)] <- 0
tempDataSyncS$flowS[is.na(tempDataSyncS$flowS)] <- 0

# doY as an integer
tempDataSyncS$dOYInt <- as.numeric(strftime(tempDataSyncS$date, format = "%j"))
```

```{r dummy site variable}

tempDataSyncS$river0 <- ifelse( tempDataSyncS$riverOrdered=='WEST BROOK',1,0 ) # not really needed
tempDataSyncS$river1 <- ifelse( tempDataSyncS$riverOrdered=='WB JIMMY',1,0 )
tempDataSyncS$river2 <- ifelse( tempDataSyncS$riverOrdered=='WB MITCHELL',1,0 )
tempDataSyncS$river3 <- ifelse( tempDataSyncS$riverOrdered=='WB OBEAR',1,0 )

tempDataSyncS$site0 <- ifelse( tempDataSyncS$site=='MAUSGS_SEC30_DL',1,0 ) # not really needed
tempDataSyncS$site1 <- ifelse( tempDataSyncS$site=='MAUSGS_SEC45_DL',1,0 )
tempDataSyncS$site2 <- ifelse( tempDataSyncS$site=='MAUSGS_SEC6_DL',1,0 )
tempDataSyncS$site3 <- ifelse( tempDataSyncS$site=='MAUSGS_WB_JIMMY',1,0 )
tempDataSyncS$site4 <- ifelse( tempDataSyncS$site=='MAUSGS_WB_MITCHELL',1,0 )
tempDataSyncS$site5 <- ifelse( tempDataSyncS$site=='MAUSGS_WB_OBEAR',1,0 )
tempDataSyncS$site6 <- ifelse( tempDataSyncS$site=='MAUSGS_WEST_BROOK',1,0 )

```

```{r raw data graphs}

ggplot(tempDataSyncS,aes(date,temp))+
  geom_point()+
  geom_point(aes(date,airTemp))+
  geom_point(aes(date,flowS),color='red')+
  facet_wrap(~site)

ggplot(tempDataSyncS,aes(dOY,temp))+
  geom_point(aes(color=factor(year)))+
  geom_line(aes(color=factor(year)))+
  facet_wrap(~site)

```

```{r subset data}

tempDataSyncS <- filter(tempDataSyncS
                        , year > 2005  
                        #,site == 'MAUSGS_SEC_45_DL'
                        #,site == 'MAUSGS_WB_MITCHELL' 
                        )#'MAUSGS_WEST_BROOK')

tempDataSyncS$rowNum <- 1:dim(tempDataSyncS)[1]

firstObsRows <- tempDataSyncS %>%
                  group_by(site,year) %>%
                  filter(date == min(date))%>%
                  select(rowNum)

evalRows <- tempDataSyncS %>%
                  group_by(site,year) %>%
                  filter(date != min(date))%>%
                  select(rowNum)
```


```{r run JAGS model}

# try moving mean air T?
data.fixed <- data.frame(intercept = 1
                         ,airTemp = tempDataSyncS$airTemp 
                         ,airTempLag1 = tempDataSyncS$airTempLagged1
                         ,airTempLag2 = tempDataSyncS$airTempLagged2
                         
                         ,flow = tempDataSyncS$flowS
                         
                         ,airFlow = tempDataSyncS$airTemp * tempDataSyncS$flowS
#                         ,air1Flow = tempDataSyncS$airTempLagged1 * tempDataSyncS$flowS
#                         ,air2Flow = tempDataSyncS$airTempLagged2 * tempDataSyncS$flowS
                         
                         #main site effects
                         ,site1 = tempDataSyncS$site1
                         ,site2 = tempDataSyncS$site2
                         ,site3 = tempDataSyncS$site3
                         ,site4 = tempDataSyncS$site4
                         ,site5 = tempDataSyncS$site5
                         ,site6 = tempDataSyncS$site6
                         
                         #site interaction with air temp
                         ,site1Air = tempDataSyncS$site1 * tempDataSyncS$airTemp
                         ,site2Air = tempDataSyncS$site2 * tempDataSyncS$airTemp
                         ,site3Air = tempDataSyncS$site3 * tempDataSyncS$airTemp
                         ,site4Air = tempDataSyncS$site4 * tempDataSyncS$airTemp
                         ,site5Air = tempDataSyncS$site5 * tempDataSyncS$airTemp
                         ,site6Air = tempDataSyncS$site6 * tempDataSyncS$airTemp
                         
                         
                         # site interaction with flow
                         ,site1Flow = tempDataSyncS$site1 * tempDataSyncS$flowS
                         ,site2Flow = tempDataSyncS$site2 * tempDataSyncS$flowS
                         ,site3Flow = tempDataSyncS$site3 * tempDataSyncS$flowS
                         ,site4Flow = tempDataSyncS$site4 * tempDataSyncS$flowS
                         ,site5Flow = tempDataSyncS$site5 * tempDataSyncS$flowS
                         ,site6Flow = tempDataSyncS$site6 * tempDataSyncS$flowS
                         
#                          
                          )

data.random.years <- data.frame(intercept.year = 1, 
                     dOY = tempDataSyncS$dOY, 
                     dOY2 = tempDataSyncS$dOY^2,
                     dOY3 = tempDataSyncS$dOY^3
                     )

monitor.params <- c("residuals",
            "deviance",
            "sigma",
            "B.0",
            "B.year",
            "rho.B.year",
            "mu.year",
            "sigma.b.year",
            "stream.mu",
            "ar1" #,
    #        "ar1Mean",
    #        "ar1SD"
            )

coda.tf <- T # currently only works in full for TRUE (using coda.samples)
system.time(M.wb <- modelRegionalTempWB(tempDataSyncS, data.fixed=data.fixed, data.random.years=data.random.years, n.burn = 1000, n.it = 1000, n.thin = 5, nc = 3, coda = coda.tf, param.list = monitor.params))

rm(ggs.wb)
ggs.wb <- ggs(M.wb)
#ggs_traceplot(ggs.wb, family = "deviance")
#ggs_traceplot(ggs.wb, family = "B.0")
#ggs_density(ggs.wb, family = "B.0")

#save(M.wb, file = paste0(dataLocalDir, "westbrook-mcmc.RData"))

huc.mat <- as.matrix(M.wb)
tempDataSyncS$resid.wb <- NA
tempDataSyncS$pred.wb <- NA
for(i in 1:length(tempDataSyncS$temp)) {
  tempDataSyncS$resid.wb[i] <- mean(huc.mat[ , paste0("residuals[", i, "]")])
  tempDataSyncS$pred.wb[i] <- mean(huc.mat[ , paste0("stream.mu[", i, "]")])
}
rm(rmse)
(rmse <- sqrt(sum(tempDataSyncS$resid.wb^2)/length(tempDataSyncS$resid.wb)) )
# 0.988 no Ar
# 0.729 w ar1

means <- ggs.wb %>%
  group_by(Parameter)%>%
  summarise(mean=mean(value),sd=sd(value))

beep()
```

```{r predictions of cubic by year}

bYear <- means[25:52,]
bYear$year <- substring(bYear$Parameter,8,8)
bYear$p <- substring(bYear$Parameter,10,10)
bYear$m <- bYear$mean #can't use 'mean' in dcast
bY <- dcast(bYear, year~p,value=m)
bY$year <- as.numeric(bY$year)
names(bY) <- c('year','int','q1','q2','q3')

predCubic1 <- data.frame(dOY=rep(unique(tempDataSyncS$dOY),dim(bY)[1]),
                        year=rep(1:7, each=length(unique(tempDataSyncS$dOY)))
                        )
                    
predCubic <- left_join(predCubic1,bY)
predCubic$pred <- predCubic$int + predCubic$q1 * predCubic$dOY + 
                                  predCubic$q2 * predCubic$dOY^2 +
                                  predCubic$q3 * predCubic$dOY^3


ggplot(predCubic, aes(dOY,pred)) + geom_line(aes(color=factor(year)),size=1.5)
```


## Evaluate MCMC Iterations
```{r check model convergence and mixing}


# this saves a pdf file
ggmcmc(ggs.wb, file = "ggmcmc-wb.pdf", family = "B.0", plot = c("ggs_density",  "ggs_traceplot", "ggs_running", "ggs_compare_partial", "ggs_autocorrelation", "ggs_crosscorrelation", "ggs_Rhat", "ggs_geweke", "ggs_caterpillar"))
dev.off()

ggmcmc(ggs.wb, file = "ggmcmc-wb.pdf", family = "B.year", plot = c("ggs_density",  "ggs_traceplot", "ggs_running", "ggs_compare_partial", "ggs_autocorrelation", "ggs_crosscorrelation", "ggs_Rhat", "ggs_geweke", "ggs_caterpillar"))
dev.off()

ggs_traceplot(ggs.wb[ggs.wb$Parameter %in% c('B.0[1]','B.0[2]','B.0[3]','B.0[4]','B.0[5]','B.0[6]'),], family = "B.0")
ggs_density(ggs.wb, family = "B.0")
ggs_crosscorrelation(ggs.wb, family = "B.0")

ggs_density(ggs.wb, family="B.year")
ggs_traceplot(ggs.wb, family = "B.year")

ggs_traceplot(ggs.wb, family = "ar1")
ggs_density(ggs.wb, family="ar1")

mean(ggs.wb[ggs.wb$Parameter == 'ar1[2]','value'])
mean(ggs.wb[ggs.wb$Parameter == 'ar1Mean','value'])



```

## Check model fit
```{r check model fit}
#------ Check residual patterns------
# Observed vs Residuals
g <- ggplot(tempDataSyncS, aes(temp, resid.wb)) 
g + geom_point(aes(color=factor(year)),alpha = 0.3) + geom_smooth() + theme_bw()


#observed vs. predicted
ggplot(tempDataSyncS, aes(temp, pred.wb)) +
  geom_point(alpha = 0.3) + 
  geom_abline(intercept=0,slope=1) + 
  theme_bw() +
  facet_grid(year~site)

yearPlot <- 2008
ggplot(tempDataSyncS[tempDataSyncS$year==yearPlot
   #                  &  tempDataSyncS$site == 'MAUSGS_WB_MITCHELL'
                     &  tempDataSyncS$site == 'MAUSGS_SEC_45_DL'
                     ,], aes(dOY, pred.wb)) + 
  geom_point(aes(dOY,temp),color='red')+
  geom_line(aes(dOY,temp),color='red')+
  geom_line(aes(dOY,(airTemp+4)*5),color='blue')+
 # geom_line(aes(dOY,pred),data=predCubic[predCubic$year==yearPlot-2005,])+
   geom_line(aes(dOY,pred,color=factor(year)),data=predCubic)+
  geom_point() 
  #facet_wrap(site~year)



library(hexbin)
g + stat_binhex(bins = 100) + geom_smooth() + theme_bw()

g + geom_point() + geom_density2d()

# Residuals by random year
b <- ggplot(tempDataSyncS, aes(x = factor(year), y = resid.wb))
b + geom_boxplot() + coord_flip()

# Residuals by covariates
ggplot(tempDataSyncS, aes(airTemp, resid.wb)) + geom_point(alpha = 0.5) + geom_smooth() + theme_bw() + facet_wrap(~site)

ggplot(tempDataSyncS[tempDataSyncS$year==2010,], aes(dOY, resid.wb)) + geom_point(alpha = 0.5) + geom_smooth() + theme_bw()+ facet_grid(site~.)

ggplot(tempDataSyncS, aes(dOY^2, resid.wb)) + geom_point(alpha = 0.5) + geom_smooth() + theme_bw()

# correlation in MCMC for residuals
acf(huc.mat[ , "residuals[1]"], lag.max = 40, xlab = "Lag", ylab = "Correlation", main = "")
acf(huc.mat[ , "residuals[2]"], lag.max = 40, xlab = "Lag", ylab = "Correlation", main = "")

# correlation in residuals over time 
acf(tempDataSyncS$resid.wb, lag.max = 100, xlab = "Lag", ylab = "Correlation", main = "") # 

```


```{r ending info}

print(sessionInfo())

```

